services:
  app:
    profiles: ["app"]
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - localstack
      - redis
      - seq
    environment:
      - SEQ_URL=http://seq:5341
      - AWS_ENDPOINT=http://localstack:4566
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY=test
      - AWS_SECRET_KEY=test
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - API_KEY=demo-dev-key

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,secretsmanager
      - DEBUG=1

  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"     # Web UI
      - "5342:5341"   # Ingest API
    environment:
      - ACCEPT_EULA=Y

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped